### ISSUE TITLE
`engine->getNbBindings() == 2' failed

### ISSUE THREAD

**Issue by ZhangChaoZhong** [linghu8812/tensorrt_inference#3]
Hello! I have such a problem: as shown in the figure below.
Can you help me solve it? thank you!
![图片](https://user-images.githubusercontent.com/30583522/99945482-aa065300-2daf-11eb-979c-3ef186561136.png

**Comment by linghu8812** [comment]
@ZhangChaoZhong Hello，please export yolov5 onnx with the instruction in the [yolov5/README](https://github.com/linghu8812/tensorrt_inference/blob/master/yolov5/README.md#2export-onnx-model), use my [yolov5 repo](https://github.com/linghu8812/yolov5) to export yolov5 onnx instead of the official yolov5. The `yolo.py` file has a little difference

**Comment by ZhangChaoZhong** [comment]
Thank you for your answer.
